# Generated by Django 6.0 on 2026-03-27 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_username_verificationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpage',
            name='module',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='feewaiver',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='feewaiver',
            name='user',
        ),
        migrations.RemoveField(
            model_name='module',
            name='course',
        ),
        migrations.RemoveField(
            model_name='practicepaper',
            name='module',
        ),
        migrations.RemoveField(
            model_name='flashcardset',
            name='module',
        ),
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.course'),
        ),
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.university'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('owner', 'Owner')], default='student', max_length=20),
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_content', models.BooleanField(default=False)),
                ('can_view_expert_messages', models.BooleanField(default=False)),
                ('is_global', models.BooleanField(default=False)),
                ('scoped_courses', models.ManyToManyField(blank=True, related_name='admin_profiles', to='core.course')),
                ('scoped_universities', models.ManyToManyField(blank=True, related_name='admin_profiles', to='core.university')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContentNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('node_type', models.CharField(max_length=50)),
                ('body', models.JSONField(blank=True, default=dict)),
                ('order', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.contentnode')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='node',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_set', to='core.contentnode'),
        ),
        migrations.AddField(
            model_name='practicepaper',
            name='node',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practice_paper', to='core.contentnode'),
        ),
        migrations.CreateModel(
            name='CourseExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experts', to='core.course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tab_type', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='core.course')),
            ],
        ),
        migrations.AddField(
            model_name='contentnode',
            name='tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='core.coursetab'),
        ),
        migrations.CreateModel(
            name='ExpertQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_questions', to='core.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asked_questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpertMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.expertquestion')),
            ],
        ),
        migrations.CreateModel(
            name='PreApprovedWaiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waivers', to='core.course')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waivers', to='core.university')),
            ],
            options={
                'unique_together': {('email', 'university', 'course')},
            },
        ),
        migrations.DeleteModel(
            name='AdminPermission',
        ),
        migrations.DeleteModel(
            name='ContentPage',
        ),
        migrations.DeleteModel(
            name='FeeWaiver',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
